### ISSUE TITLE
Question: Multiple first-level entries in sidebar?

### ISSUE THREAD

**Issue by elenalenaelena** [vsoch/docsy-jekyll#12]
Hi, 
I was trying to add multiple first level entries in the sidebar. This should be possible by modyfying the `toc.yml` file but resulted in nested unordered lists. As far as I can see there are some </li> and </ul> closing tags missing in the `sidebar.html` file.

**Comment by vsoch** [comment]
hey @elenalenaelena - if you look at conversation in #3, this has come up before, and the reason is because the design is intended to mimic the real docsy as much as we possibly can. If you look at the example here https://example.docsy.dev/docs/, akin to what we have here, there is one main title at the top, and then link groups with one level of children.

**Comment by elenalenaelena** [comment]
Thank you @vsoch for clarifying this. Unlike [#3](https://github.com/vsoch/docsy-jekyll/issues/3) my question was not on the topic of nesting in general but only on the first-level items. Anyways I can understand the reason for this now.

**Comment by vsoch** [comment]
Sure thing! Yeah, the first level (the top item) is only represented once on Docsy. If you find an example with docsy where this isn't the case / or there is some way to customize Docsy to support it, then we could add it here too. I'll leave the issue open in case others want to investigate.

**Comment by vsoch** [comment]
I don't think this is being done upstream, so I'm going to close here. If anyone finds examples, please still post and we can update / reopen the issue. Thanks!
